### ISSUE TITLE
Generated images are distorted and not of high quality

### ISSUE THREAD

**Issue by Thiru-Malai** [David-Lor/dalle-mini-telegram-bot#20]
![IMG_20230201_064306_294.jpg](https://user-images.githubusercontent.com/73980589/215920786-7d31fb58-4dea-4184-9433-3a3882860829.jpg)

![IMG_20230201_064352_557.jpg](https://user-images.githubusercontent.com/73980589/215920879-e23a74a7-887d-48e7-9520-9740bbdec48e.jpg)

All the images are similar to this.
 
How to solve this?

**Comment by David-Lor** [comment]
That's how dalle-mini works. If you want higher quality, you should use other AI, such as OpenAI's DALLE ir stable diffusion.

**Comment by Thiru-Malai** [comment]
Okay. So is it possible to make changes in  your code to use Stable Diffusion ?

**Comment by David-Lor** [comment]
> Okay. So is it possible to make changes in your code to use Stable Diffusion ?

It's possible, indeed. I've also found GitHub repositories with Stable Diffusion Telegram bots.
