### ISSUE TITLE
Bot not responding in channel

### ISSUE THREAD

**Issue by Dausstic** [David-Lor/dalle-mini-telegram-bot#8]
Not sure what caused it; it was working earlier and suddenly it stopped responding to commands in the group chat. It still works just fine when given commands in PM, just has stopped responding in group chat, even after being removed and readded to the group.

**Comment by David-Lor** [comment]
@Dausstic Is it possible that you've added more bots to the group? (is it a channel or a group?) In which case you should write the command with a mention to the bot, like `/generate@dalle_mini_bot darth vader surfing`

**Comment by Dausstic** [comment]
> @Dausstic Is it possible that you've added more bots to the group? (is it a channel or a group?) In which case you should write the command with a mention to the bot, like `/generate@dalle_mini_bot darth vader surfing`

That did indeed work. That's very strange, because it was working before with just /generate, even with other bots present in the channel. Interesting, but thank you for helping with that.

**Comment by David-Lor** [comment]
Nice :smile: Sometimes bots in groups have weird behaviour
